spring:
  application:
    name: api-rede-social
  datasource:
    url: jdbc:h2:mem:api-rede-social
    driver-class-name: org.h2.Driver
    username: sa
    password:

api:
  security:
    token:
      secret: my-secret