spring:
  application:
    name: api-rede-social
  datasource:
    url: jdbc:h2:mem:api-rede-social
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

api:
  security:
    token:
      secret: my-secret